[workspace]
members = [
    "aqd-core",
    "aqd-polkadot",
    "aqd-solana",
    "aqd-utils",
    "solana-contracts",
]

default-members = [
    "aqd-core",
    "aqd-polkadot",
    "aqd-solana",
    "aqd-utils",
    "solana-contracts",
]

resolver = "2"
