name: Aqd CI

on:
  push:
    # Run on main and solana branches
    branches: [main, solana]
  pull_request:
    branches: [main]
  # Run every Monday at 1:30 AM UTC
  schedule:
    - cron: '30 1 * * 1'

jobs:
  build:
    name: Sanity Check Codebase
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    # Install libudev (required for solana crates)
    - name: Install libudev
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Check formatting
      run: |
        cargo fmt -- --check

    - name: Check linting
      run: |
        cargo clippy

    - name: Build and test
      run: |
        cargo test

  solana:
    name: Solana Integration Testing
    runs-on: ubuntu-latest

    steps:
    # Install jq to parse JSON (used in shell scripts)
    - name: Install jq 
      run: |
        sudo apt-get update
        sudo apt-get install -y jq libudev-dev

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    # Set up Solana CLI 
    - name: Set up Solana CLI
      working-directory: ./integration/solana
      run: ./setup_solana.sh
    
    # Compile Aqd in release mode
    - name: Compile Aqd 
      run: |
        cargo build --release
   
    # Run Solana integration tests
    - name: Test Solana CLI
      run: ./solana_cli.sh
      working-directory: ./integration/solana
